AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AsfNetworkCidr:
    Type: String
    NoEcho: true

  DatabasePassword:
    Type: String
    NoEcho: true

Resources:
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20' # TODO depends on StorageType?
      DBInstanceClass: 'db.t3.micro' # TODO different class for prod?
      DBSecurityGroups:
        - !Ref DatabaseSecurityGroup
      Engine: postgres
      EngineVersion: '14.4'
      MasterUsername: postgres
      MasterUserPassword: !Ref DatabasePassword
      # TODO: MaxAllocatedStorage: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html#cfn-rds-dbinstance-maxallocatedstorage
      Port: '5432'
      # TODO: ProcessorFeatures: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html#cfn-rds-dbinstance-processorfeatures
      PubliclyAccessible: true
      # TODO: StorageType: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html#cfn-rds-dbinstance-storagetype

  DatabaseSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      DBSecurityGroupIngress:
        - CIDRIP: !Ref AsfNetworkCidr
      GroupDescription: Allows incoming connections from within the ASF network.
