name: asf-stac
channels:
  - hyp3
  - conda-forge
  - nodefaults
dependencies:
  - boto3
  - botocore
  - python
  - pip
  # For packaging, and testing
  - flake8
  - flake8-import-order
  - flake8-blind-except
  - flake8-builtins
  - pytest
  - pytest-console-scripts
  - pytest-cov
  # For running
  - pystac
  - shapely
