AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

  CidrIp:
    Type: String

  DatabaseAdminPassword:
    Type: String
    NoEcho: true

  DatabaseReadPassword:
    Type: String
    NoEcho: true

Outputs:
  BuildProject:
    Value: !GetAtt Database.Outputs.BuildProject

Resources:
  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DatabaseHost: !GetAtt Database.Outputs.DatabaseHost
        DatabaseReadPassword: !Ref DatabaseReadPassword
        SecurityGroupId: !GetAtt Database.Outputs.ClientSecurityGroupId
        SubnetIds: !Join [",", !Ref SubnetIds]
      TemplateURL: api/cloudformation.yml

  Database:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DatabaseAdminPassword: !Ref DatabaseAdminPassword
        DatabaseReadPassword: !Ref DatabaseReadPassword
        VpcId: !Ref VpcId
        SubnetIds: !Join [",", !Ref SubnetIds]
        CidrIp: !Ref CidrIp
      TemplateURL: database/cloudformation.yml
