AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DatabasePassword:
    Type: String
    NoEcho: true

Outputs:
  DatabaseHost:
    Value: !GetAtt Database.Outputs.DatabaseHost

Resources:
  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DatabaseHost: !GetAtt Database.Outputs.DatabaseHost
        DatabasePassword: !Ref DatabasePassword
      TemplateURL: api/cloudformation.yml

  Database:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DatabasePassword: !Ref DatabasePassword
      TemplateURL: database/cloudformation.yml
