AWSTemplateFormatVersion: 2010-09-09

Parameters:
  DatabaseAdminPassword:
    Type: String
    NoEcho: true

  DatabaseReadPassword:
    Type: String
    NoEcho: true

Outputs:
  DatabaseHost:
    Value: !GetAtt Database.Outputs.DatabaseHost

Resources:
  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DatabaseHost: !GetAtt Database.Outputs.DatabaseHost
        DatabaseReadPassword: !Ref DatabaseReadPassword
      TemplateURL: api/cloudformation.yml

  Database:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DatabaseAdminPassword: !Ref DatabaseAdminPassword
      TemplateURL: database/cloudformation.yml
