name: Deploy STAC API

on:
  push:
    branches:
      - sandbox

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CF_TEMPLATES_BUCKET: ${{ secrets.CF_TEMPLATES_BUCKET }}
  CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
  DB_ADMIN_PASSWORD: ${{ secrets.DB_ADMIN_PASSWORD }}
  DB_INGEST_PASSWORD: ${{ secrets.DB_INGEST_PASSWORD }}
  DB_READ_PASSWORD: ${{ secrets.DB_READ_PASSWORD }}
  STACK_NAME: stac-api-sandbox

jobs:
  deploy-stac-api:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Lambda dependencies
        run: make -s install-lambda-deps
      - name: Install pyPgSTAC
        run: make -s install-pypgstac
      - name: Deploy CloudFormation stack
        run: |
          make -s deploy \
            s3_bucket=${{ env.CF_TEMPLATES_BUCKET }} \
            stack_name=${{ env.STACK_NAME }} \
            cloudformation_role_arn=${{ env.CLOUDFORMATION_ROLE_ARN }} \
            db_admin_password=${{ env.DB_ADMIN_PASSWORD }}
      - name: Get database host
        run: |
          echo "DATABASE_HOST=$(aws cloudformation describe-stacks \
                                --stack-name $STACK_NAME \
                                --query 'Stacks[0].Outputs[?OutputKey==`DatabaseHost`].OutputValue' \
                                --output text)" >> $GITHUB_ENV
      - name: Install or upgrade PostGIS
        run: make -s install-or-upgrade-postgis db_host=$DATABASE_HOST db_admin_password=${{ env.DB_ADMIN_PASSWORD }}
      - name: Install or upgrade PgSTAC
        run: make -s pypgstac-migrate db_host=$DATABASE_HOST db_admin_password=${{ env.DB_ADMIN_PASSWORD }}
      - name: Configure database roles
        run: |
          make -s configure-database-roles \
            db_host=$DATABASE_HOST \
            db_admin_password=${{ env.DB_ADMIN_PASSWORD }} \
            db_ingest_password=${{ env.DB_INGEST_PASSWORD }} \
            db_read_password=${{ env.DB_READ_PASSWORD }}
