name: Deploy STAC API

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-stac-api:
    runs-on: ubuntu-latest
    if: github.ref == matrix.deploy_ref
    strategy:
      matrix:
        include:
          - environment: asf-stac-test
            deploy_ref: refs/heads/develop
            template_bucket: cf-templates-aubvn3i9olmk-us-west-2
            github_branch: develop
            domain_name: stac-test.asf.alaska.edu

          - environment: asf-stac
            deploy_ref: refs/heads/main
            template_bucket: cf-templates-aubvn3i9olmk-us-west-2
            github_branch: main
            domain_name: stac.asf.alaska.edu

    environment:
      name: ${{ matrix.environment }}

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Lambda dependencies
        run: make -s install-lambda-deps
      - name: Install Python dependencies for deployment scripts
        run: python -m pip install -r requirements-run-codebuild.txt
      - name: Deploy CloudFormation stack
        run: |
          make -s deploy \
            stack_name=${{ matrix.environment }} \
            s3_bucket=${{ matrix.template_bucket }} \
            cloudformation_role_arn=${{ secrets.CLOUDFORMATION_ROLE_ARN }} \
            db_admin_password=${{ secrets.DB_ADMIN_PASSWORD }} \
            db_read_password=${{ secrets.DB_READ_PASSWORD }} \
            cidr_ip=${{ secrets.CIDR_IP }} \
            github_branch=${{ matrix.github_branch }} \
            domain_name=${{ matrix.domain_name }} \
            certificate_arn=${{ secrets.CERTIFICATE_ARN }}
      - name: Get CodeBuild project
        run: |
          echo "CODEBUILD_PROJECT=$(aws cloudformation describe-stacks \
                                    --stack-name ${{ matrix.environment }} \
                                    --query 'Stacks[0].Outputs[?OutputKey==`BuildProject`].OutputValue' \
                                    --output text)" >> $GITHUB_ENV
      - name: Run CodeBuild
        run: python run_codebuild.py
