name: Deploy STAC API prod

on:
  push:
    branches:
      - main

jobs:
  deploy-stac-api:
    runs-on: ubuntu-latest

    environment:
      name: asf-stac

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-stac
        with:
          STACK_NAME: asf-stac
          GITHUB_BRANCH: main
          DOMAIN_NAME: stac.asf.alaska.edu

  call-bump-version-workflow:
    needs: deploy-stac-api
    uses: ASFHyP3/actions/.github/workflows/reusable-bump-version.yml@v0.4.0
    secrets:
      USER_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
