name: Run tests

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3.1.0

      - - uses: conda-incubator/setup-miniconda@v2
          with:
            mamba-version: '*'
            python-version: '3.9'
            activate-environment: asf-stac
            environment-file: environment.yml

      - name: run pytest
        run: make test
