name: Run tests

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3.1.0

      - uses: mamba-org/provision-with-micromamba@v14
        with:
          environment-file: environment.yml
          extra-specs: |
            python=3.9

      - name: run pytest
        run: make test
