name: Run tests

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: edit environment.yml
        # Edit environment.yml to specify the absolute path for requirements.txt as a workaround for
        # https://github.com/mamba-org/provision-with-micromamba/issues/108
        run: sed -i "s_requirements.txt_${PWD}/requirements.txt_" environment.yml

      - uses: mamba-org/provision-with-micromamba@v16
        with:
          environment-file: environment.yml
          extra-specs: |
            python=3.9

      - name: run pytest
        run: make test
